stages:
  - test

Type-test:
  stage: test
  image: python:3.9
  script:
    - pip install mypy
    - mypy src
  allow_failure: true

Lint-test:
  stage: test
  image: python:3.9
  script:
    - pip install flake8
    - flake8
  allow_failure: true

Unused-code-test:
  stage: test
  image: python:3.9
  script:
    - pip install vulture
    - vulture src/